name: Tests

on:
  pull_request:
    branches:
    - deploy2fly

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      AUTH_USER: admin
      AUTH_PASS: admin
      CI: "true"
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.1'
      - run: mix deps.get --only test
      - run: mix compile --warnings-as-errors
      - run: mix test
      - run: mix validate_urls
